# Lab | Data Structuring and Combining Data

## Challenge 1: Combining & Cleaning Data

In this challenge, we will be working with the customer data from an insurance company, as we did in the two previous labs. The data can be found here:
- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv

But this time, we got new data, which can be found in the following 2 CSV files located at the links below.

- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file2.csv
- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file3.csv

Note that you'll need to clean and format the new data.

Observation:
- One option is to first combine the three datasets and then apply the cleaning function to the new combined dataset
- Another option would be to read the clean file you saved in the previous lab, and just clean the two new files and concatenate the three clean datasets

In [2]:
import pandas as pd

In [10]:
df1 = pd.read_csv("insurance_df.csv")
df2 = pd.read_csv('https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file2.csv')
df3 = pd.read_csv('https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file3.csv')

In [12]:
df2.rename(columns = {'ST': 'state'}, inplace = True)

In [13]:
df3.rename(columns = {'ST': 'state'}, inplace = True)

In [14]:
df2.columns = df2.columns.str.lower()

In [15]:
df3.columns = df3.columns.str.lower()

In [16]:
df2.columns = df2.columns.str.replace(" ","_")

In [17]:
df3.columns = df3.columns.str.replace(" ","_")

In [20]:
gender_mapping = {'F':'F','M':'M','Femal':'F', 'Male':'M','female':'F'}
df2['gender'] = df2['gender'].map(gender_mapping)

In [21]:
df3['gender'] = df3['gender'].map(gender_mapping)

In [25]:
state_mapping = {'Washington':'Washington',
                 'Arizona':'Arizona',
                 'Nevada':'Nevada', 
                 'California':'California',
                 'Cali':'California', 
                 'AZ':'Arizona',
                 'WA':'Washington',
                 'Oregon':'Oregon'
}
df2['state'] = df2['state'].map(state_mapping)

In [28]:
df3['state'] = df3['state'].map(state_mapping)

In [29]:
df3['state'].unique()

array(['Washington', 'Arizona', 'Nevada', 'California', 'Oregon'],
      dtype=object)

In [30]:
df2['education']=df2['education'].replace("Bachelors", 'Bachelor')

In [31]:
df3['education']=df3['education'].replace("Bachelors", 'Bachelor')

In [35]:
df2['customer_lifetime_value']=df2['customer_lifetime_value'].str.replace("%","")

In [39]:
df2['vehicle_class']=df2['vehicle_class'].replace({"Luxury Car": 'Luxury', "Sports Car": "Luxury", "Luxury SUV":"Luxury"})

In [40]:
df3['vehicle_class']=df3['vehicle_class'].replace({"Luxury Car": 'Luxury', "Sports Car": "Luxury", "Luxury SUV":"Luxury"})

In [49]:
df3['vehicle_class'].unique()

array(['Two-Door Car', 'Four-Door Car', 'SUV', 'Luxury'], dtype=object)

In [50]:
df2["customer_lifetime_value"] = df2.customer_lifetime_value.apply(float)

In [51]:
df3["customer_lifetime_value"] = df3.customer_lifetime_value.apply(float)

In [52]:
df2['number_of_open_complaints'] = df2['number_of_open_complaints'].apply(lambda x: x.split("/")[1]if type(x)==str else x)

In [53]:
df3['number_of_open_complaints'] = df3['number_of_open_complaints'].apply(lambda x: x.split("/")[1]if type(x)==str else x)

In [67]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4008 entries, 0 to 4007
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customer                   1071 non-null   object
 1   state                      1071 non-null   object
 2   gender                     954 non-null    object
 3   education                  1071 non-null   object
 4   customer_lifetime_value    1068 non-null   float64
 5   income                     1071 non-null   float64
 6   monthly_premium_auto       1071 non-null   float64
 7   number_of_open_complaints  1071 non-null   float64
 8   policy_type                1071 non-null   object
 9   vehicle_class              1071 non-null   object
 10  total_claim_amount         1071 non-null   float64
dtypes: float64(5), object(6)
memory usage: 344.6+ KB

In [68]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 996 entries, 0 to 995
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customer                   996 non-null    object
 1   state                      996 non-null    object
 2   gender                     991 non-null    object
 3   education                  996 non-null    object
 4   customer_lifetime_value    992 non-null    float64
 5   income                     996 non-null    int64
 6   monthly_premium_auto       996 non-null    int64
 7   number_of_open_complaints  996 non-null    object
 8   total_claim_amount         996 non-null    float64
 9   policy_type                996 non-null    object
 10  vehicle_class              996 non-null    object
dtypes: float64(2), int64(2), object(7)
memory usage: 85.7+ KB

In [69]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7070 entries, 0 to 7069
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customer                   7070 non-null   object
 1   state                      7070 non-null   object
 2   customer_lifetime_value    7070 non-null   float64
 3   education                  7070 non-null   object
 4   gender                     7070 non-null   object
 5   income                     7070 non-null   int64
 6   monthly_premium_auto       7070 non-null   int64
 7   number_of_open_complaints  7070 non-null   int64
 8   policy_type                7070 non-null   object
 9   total_claim_amount         7070 non-null   float64
 10  vehicle_class              7070 non-null   object
dtypes: float64(2), int64(3), object(6)
memory usage: 607.7+ KB

In [54]:
df2['number_of_open_complaints'].apply(float)

0      0.0
1      0.0
2      0.0
3      1.0
4      0.0
      ...
991    0.0
992    0.0
993    0.0
994    0.0
995    0.0
Name: number_of_open_complaints, Length: 996, dtype: float64

In [56]:
df3['number_of_open_complaints'].apply(float)

0       0.0
1       0.0
2       0.0
3       0.0
4       2.0
       ...
7065    0.0
7066    0.0
7067    3.0
7068    0.0
7069    0.0
Name: number_of_open_complaints, Length: 7070, dtype: float64

In [70]:
df4 = pd.concat([df1,df2,df3], axis = 0)

In [184]:
df4.info()

<class 'pandas.core.frame.DataFrame'>
Index: 12074 entries, 0 to 7069
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customer                   9137 non-null   object
 1   state                      9137 non-null   object
 2   gender                     9015 non-null   object
 3   education                  9137 non-null   object
 4   customer_lifetime_value    9130 non-null   float64
 5   income                     9137 non-null   float64
 6   monthly_premium_auto       9137 non-null   float64
 7   number_of_open_complaints  9137 non-null   object
 8   policy_type                9137 non-null   object
 9   vehicle_class              9137 non-null   object
 10  total_claim_amount         9137 non-null   float64
dtypes: float64(4), object(7)
memory usage: 1.1+ MB

# Challenge 2: Structuring Data

In this challenge, we will continue to work with customer data from an insurance company, but we will use a dataset with more columns, called marketing_customer_analysis.csv, which can be found at the following link:

https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis_clean.csv

This dataset contains information such as customer demographics, policy details, vehicle information, and the customer's response to the last marketing campaign. Our goal is to explore and analyze this data by performing data cleaning, formatting, and structuring.

In [3]:
new_url = ('https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis_clean.csv')
mark_df = pd.read_csv(new_url)

In [4]:
mark_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10910 entries, 0 to 10909
Data columns (total 27 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   unnamed:_0                     10910 non-null  int64
 1   customer                       10910 non-null  object
 2   state                          10910 non-null  object
 3   customer_lifetime_value        10910 non-null  float64
 4   response                       10910 non-null  object
 5   coverage                       10910 non-null  object
 6   education                      10910 non-null  object
 7   effective_to_date              10910 non-null  object
 8   employmentstatus               10910 non-null  object
 9   gender                         10910 non-null  object
 10  income                         10910 non-null  int64
 11  location_code                  10910 non-null  object
 12  marital_status                 10910 non-null  object
 13  monthly_premium_auto           10910 non-null  int64
 14  months_since_last_claim        10910 non-null  float64
 15  months_since_policy_inception  10910 non-null  int64
 16  number_of_open_complaints      10910 non-null  float64
 17  number_of_policies             10910 non-null  int64
 18  policy_type                    10910 non-null  object
 19  policy                         10910 non-null  object
 20  renew_offer_type               10910 non-null  object
 21  sales_channel                  10910 non-null  object
 22  total_claim_amount             10910 non-null  float64
 23  vehicle_class                  10910 non-null  object
 24  vehicle_size                   10910 non-null  object
 25  vehicle_type                   10910 non-null  object
 26  month                          10910 non-null  int64
dtypes: float64(4), int64(6), object(17)
memory usage: 2.2+ MB

In [5]:
mark_df

,unnamed:_0,customer,state,customer_lifetime_value,response,coverage,education,effective_to_date,employmentstatus,gender,...,number_of_policies,policy_type,policy,renew_offer_type,sales_channel,total_claim_amount,vehicle_class,vehicle_size,vehicle_type,month
0,0,DK49336,Arizona,4809.216960,No,Basic,College,2011-02-18,Employed,M,...,9,Corporate Auto,Corporate L3,Offer3,Agent,292.800000,Four-Door Car,Medsize,A,2
1,1,KX64629,California,2228.525238,No,Basic,College,2011-01-18,Unemployed,F,...,1,Personal Auto,Personal L3,Offer4,Call Center,744.924331,Four-Door Car,Medsize,A,1
2,2,LZ68649,Washington,14947.917300,No,Basic,Bachelor,2011-02-10,Employed,M,...,2,Personal Auto,Personal L3,Offer3,Call Center,480.000000,SUV,Medsize,A,2
3,3,XL78013,Oregon,22332.439460,Yes,Extended,College,2011-01-11,Employed,M,...,2,Corporate Auto,Corporate L3,Offer2,Branch,484.013411,Four-Door Car,Medsize,A,1
4,4,QA50777,Oregon,9025.067525,No,Premium,Bachelor,2011-01-17,Medical Leave,F,...,7,Personal Auto,Personal L2,Offer1,Branch,707.925645,Four-Door Car,Medsize,A,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10905,10905,FE99816,Nevada,15563.369440,No,Premium,Bachelor,2011-01-19,Unemployed,F,...,7,Personal Auto,Personal L1,Offer3,Web,1214.400000,Luxury Car,Medsize,A,1
10906,10906,KX53892,Oregon,5259.444853,No,Basic,College,2011-01-06,Employed,F,...,6,Personal Auto,Personal L3,Offer2,Branch,273.018929,Four-Door Car,Medsize,A,1
10907,10907,TL39050,Arizona,23893.304100,No,Extended,Bachelor,2011-02-06,Employed,F,...,2,Corporate Auto,Corporate L3,Offer1,Web,381.306996,Luxury SUV,Medsize,A,2
10908,10908,WA60547,California,11971.977650,No,Premium,College,2011-02-13,Employed,F,...,6,Personal Auto,Personal L1,Offer1,Branch,618.288849,SUV,Medsize,A,2
10909,10909,IV32877,California,6857.519928,No,Basic,Bachelor,2011-01-08,Unemployed,M,...,3,Personal Auto,Personal L1,Offer4,Web,1021.719397,SUV,Medsize,A,1

In [6]:
mark_df.nunique()

unnamed:_0                       10910
customer                          9134
state                                5
customer_lifetime_value           8041
response                             2
coverage                             3
education                            5
effective_to_date                   59
employmentstatus                     5
gender                               2
income                            5694
location_code                        3
marital_status                       3
monthly_premium_auto               202
months_since_last_claim             37
months_since_policy_inception      100
number_of_open_complaints            7
number_of_policies                   9
policy_type                          3
policy                               9
renew_offer_type                     4
sales_channel                        4
total_claim_amount                5106
vehicle_class                        6
vehicle_size                         3
vehicle_type                         1
month                                2
dtype: int64

1. You work at the marketing department and you want to know which sales channel brought the most sales in terms of total revenue. Using pivot, create a summary table showing the total revenue for each sales channel (branch, call center, web, and mail).
Round the total revenue to 2 decimal points.  Analyze the resulting table to draw insights.

In [7]:
pivot_df = mark_df.pivot_table(index='sales_channel', values = ['monthly_premium_auto'], aggfunc ='sum')

In [8]:
pivot_df = pivot_df.round(2)

In [9]:
pivot_df

               monthly_premium_auto
sales_channel
Agent                        386335
Branch                       280953
Call Center                  197970
Web                          151511

In [10]:
'''based on the previous table what I can see is that the monthly premium auto on the sales channel agent is way higher. 
branch is the second highest, the third is call center and the fourth is web.'''

'based on the previous table what I can see is that the monthly premium auto on the sales channel agent is way higher. \nbranch is the second highest, the third is call center and the fourth is web.'

2. Create a pivot table that shows the average customer lifetime value per gender and education level. Analyze the resulting table to draw insights.

In [11]:
pivot_df2 = mark_df.pivot_table(index=['gender'], columns = 'education', values = ['customer_lifetime_value'])

In [21]:
pivot_df2.T
#transpose function, in order to switch the columsn with the index

gender                                                  F            M
                        education
customer_lifetime_value Bachelor              7874.269478  7703.601675
                        College               7748.823325  8052.459288
                        Doctor                7328.508916  7415.333638
                        High School or Below  8675.220201  8149.687783
                        Master                8157.053154  8168.832659

In [13]:
'''based on this table we can see that the female lifetime value is slightly higher on the females, 
and that the highschool or below level of education has the highest customer lifetime value, the lowest would be a doctor for both of them'''

'based on this table we can see that the female lifetime value is slightly higher on the females, \nand that the highschool or below level of education has the highest customer lifetime value, the lowest would be a doctor for both of them'

## Bonus

You work at the customer service department and you want to know which months had the highest number of complaints by policy type category. Create a summary table showing the number of complaints by policy type and month.
Show it in a long format table.

*In data analysis, a long format table is a way of structuring data in which each observation or measurement is stored in a separate row of the table. The key characteristic of a long format table is that each column represents a single variable, and each row represents a single observation of that variable.*

*More information about long and wide format tables here: https://www.statology.org/long-vs-wide-data/*

In [29]:
mark_df.groupby(['policy_type','month'])['number_of_open_complaints'].sum().round()

policy_type     month
Corporate Auto  1         443.0
                2         385.0
Personal Auto   1        1728.0
                2        1454.0
Special Auto    1          87.0
                2          95.0
Name: number_of_open_complaints, dtype: float64

In [30]:
mark_df.groupby(['policy_type','month'])[['number_of_open_complaints']].sum().round() #double brackets make it a data frame

                      number_of_open_complaints
policy_type    month
Corporate Auto 1                          443.0
               2                          385.0
Personal Auto  1                         1728.0
               2                         1454.0
Special Auto   1                           87.0
               2                           95.0

In [ ]:
reset_index()'''a way of printing a dataframe. it makes the old index a new column. It shows a nice table, with reset index'''